OnBoardTask3/OnBoardTask3/Models/ProductSold.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnBoardTask3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class ProductSold
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int CustomerId { get; set; }
        public int StoreId { get; set; }
        [DisplayName("DateSold")]
        public System.DateTime DateSold { get; set; }
        public string ReturnDateForDisplay
        {
            get
            {
                return this.DateSold.ToString("dd/mm/yyyy");
            }
        }

        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
        public virtual Store Store { get; set; }

        public string CustomerName { get; internal set; }
        public string ProductName { get; internal set; }
        public string StoreName { get; internal set; }
    }
}

OnBoardTask3/OnBoardTask3/Controllers/ProductSoldController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnBoardTask3.Models;

namespace KnockOutMVC.Controllers
{
    public class ProductSoldsController : Controller
    {
        private CRUDTaskEntities db = new CRUDTaskEntities();

        // GET: ProductSolds
        public ActionResult Index()
        {
            return View();
        }
        //GET All ProductSoldList
        public JsonResult ProductSoldList()
        {
            
            var sale = db.ProductSolds.Select(x => new KOClass
            {
                Id = x.Id,
                CustomerId = x.CustomerId,
                ProductId = x.ProductId,
                DateSold = x.DateSold,
                CustomerName = x.Customer.CustomerName,
                ProductName = x.Product.ProductName,
                StoreName = x.Store.StoreName,

            });
            return Json(sale, JsonRequestBehavior.AllowGet);
        }

        // GET: ProductSolds/Details/5
        public ActionResult Details()
        {
            return PartialView();
        }

        // GET: ProductSolds/Create
        public ActionResult Create()
        {
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "CustomerName");
            ViewBag.ProductId = new SelectList(db.Products, "ProductId", "ProductName");
            ViewBag.StoreId = new SelectList(db.Stores, "StoreId", "StoreName");
            return PartialView();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public int Create([Bind(Include = "ProductSoldID,ProductId,CustomerId,StoreId,DateSold")] ProductSold productSold)
        {
            if (ModelState.IsValid)
            {
                db.ProductSolds.Add(productSold);
                db.SaveChanges();
                return productSold.Id;
            }
            else
            {
                return 0;
            }
        }
        // GET: ProductSolds/Edit/5
        public ActionResult Edit()
        {
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "CustomerName");
            ViewBag.ProductId = new SelectList(db.Products, "ProductId", "ProductName");
            ViewBag.StoreId = new SelectList(db.Stores, "StoreId", "StoreName");
            return PartialView();
        }
        //POST: ProductSolds/Edit/5
        //To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ProductId,CustomerId,StoreId,DateSold")] ProductSold productSold)
        {
            if (ModelState.IsValid)
            {
                db.Entry(productSold).State = EntityState.Modified;
                db.SaveChanges();
                return new HttpStatusCodeResult(200, "Success");
            }
            return new HttpStatusCodeResult(404, "Unable to update.");
        }





        // GET: ProductSolds/Delete/5
        public ActionResult Delete()
        {
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "CustomerName");
            return PartialView();
        }

        // POST: ProductSolds/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int? id)
        {
            if (id != null)
            {
                ProductSold productSold = db.ProductSolds.Find(id);
                db.ProductSolds.Remove(productSold);
                db.SaveChanges();
                return new HttpStatusCodeResult(200, "Success");
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OnBoardTask3/OnBoardTask3/Views/ProductSolds/Create.cshtml
@model OnBoardTask3.Models.ProductSold
@{
    ViewBag.Title = "Create";
}
<div id="create-sale">
    <h2>Create</h2>

    @using (Html.BeginForm("Create", "ProductSolds", FormMethod.Post, new { id = "create-sale-form", action = "javascript:void(0);" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Sale</h4>
            <hr />
            <div class="form-group">
                @Html.LabelFor(model => model.Id, "ProductSoldID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("CustomerId", null, htmlAttributes: new { @class = "form-control", data_bind = "value: selectedSale.CustomerId" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ProductId, "ProductId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("ProductId", null, htmlAttributes: new { @class = "form-control", data_bind = "value: selectedSale.ProductId" })
                </div>
            </div>



            <div class="form-group">
                @Html.LabelFor(model => model.StoreId, "StoreId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("StoreId", null, htmlAttributes: new { @class = "form-control", data_bind = "value: selectedSale.StoreId" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DateSold, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DateSold, new
                    {
                        htmlAttributes = new
                        {
                            @class = "form-control",
                            data_bind = "value: selectedSale.DateSold",
                            type = "date",
                            value = "2017-11-1",
                            id = "date-picker"
                        }
                    })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" data-bind="click: saveSale" />
                </div>
            </div>
        </div>
    }

</div>

OnBoardTask3/OnBoardTask3/Views/ProductSolds/Delete.cshtml
@model OnBoardTask3.Models.ProductSold

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div id="deleteSale">
    <h4>ProductSold (Id <span data-bind="text: selectedSale.Id"></span>)</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DateSold)
        </dt>
        <dd data-bind="text: selectedSale.DateSold"></dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customer.CustomerName)
        </dt>
        <dd data-bind="text: selectedSale.CustomerName()"></dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product.ProductName)
        </dt>
        <dd data-bind="text: selectedSale.ProductName"></dd>

        <dt>
            @Html.DisplayNameFor(model => model.Store.StoreName)
        </dt>
        <dd data-bind="text: selectedSale.StoreName"></dd>


    </dl>

    @using (Html.BeginForm("Delete", "ProductSolds", FormMethod.Post, new { id = "delete-sale-form", action = "javascript:void(0);" }))
    {
        @Html.AntiForgeryToken()
        <input hidden data-bind="value: selectedSale.ProductsSoldID" id="Id" name="Id" />
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" data-bind="click: deleteConfirmed" />
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

OnBoardTask3/OnBoardTask3/Views/ProductSolds/Edit.cshtml
@model OnBoardTask3.Models.ProductSold
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "KOClass", FormMethod.Post, new { id = "edit-sale-form", action = "javascript:void(0);" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ProductSold</h4>
        <hr />
        @Html.HiddenFor(model => model.Id, htmlAttributes: new { data_bind = "value: selectedSale.Id" })
        <div class="form-group">
            @Html.LabelFor(model => model.CustomerId, "CustomerId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CustomerId", null, htmlAttributes: new
                {
                    @class = "form-control",
                    data_bind = "value: newSale.CustomerId"
                })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductId, "ProductId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProductId", null, htmlAttributes: new
                {
                    @class = "form-control",
                    data_bind = "value: newSale.ProductId"
                })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.StoreId, "StoreId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StoreId", null, htmlAttributes: new
                {
                    @class = "form-control",
                    data_bind = "value: newSale.StoreId"
                })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateSold, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateSold, new
                {
                    htmlAttributes = new
                    {
                        @class = "form-control",
                        data_bind = "value: newSale.DateSold"
                    }
                })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" data-bind="click:editConfirmed" />
            </div>
        </div>
    </div>
}

OnBoardTask3/OnBoardTask3/Views/ProductSolds/Index.cshtml
@model OnBoardTask3.Models.ProductSold

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>
<p>
    <a href="javascript:void(0);" data-bind="click: createSale"
       class="btn-create btn btn-primary">Create Sale</a>
</p>
<table class="table table-responsive table-hover table-striped table-bordered">
    <tr>
      
        <th>
            @Html.DisplayNameFor(model => model.Customer.CustomerName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Product.ProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Store.StoreName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateSold)
        </th>
        <th>Actions</th>
    </tr>

    <tbody data-bind="foreach: ProductSolds">
        <tr>
            @*<td data-bind="text: Id"></td>*@
            <td data-bind="text: CustomerName"></td>
            <td data-bind="text: ProductName"></td>
            <td data-bind="text: StoreName"></td>
            <td data-bind="text: DateSold"></td>
            <td>
                <a href="javascript:void(0);" data-bind="click: $parent.editSale"
                   class="btn-details btn btn-default">Edit</a>
                @*<a href="javascript:void(0);" data-bind="click: $parent.viewSale"
                    class="btn-edit btn btn-default">Details</a>*@
                <a href="javascript:void(0);" data-bind="click: $parent.deleteSale"
                   class="btn-delete btn btn-default">Delete</a>
            </td>
        </tr>
    </tbody>

</table>

<!-- Modal for CRUD operations -->
<div id="my-modal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-body" id="my-modal-content">
                <!-- Modal content goes here -->
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" id="clsBtn">Close</button>
            </div>
        </div>

    </div>
</div>

<!-- End CRUD Modal -->
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/knockout-3.4.2.js"></script>
<script src="~/Scripts/knockout.validation.min.js"></script>
<script src="~/Scripts/bootstrap-datepicker.js"></script>
@section scripts
{
    <script type="text/javascript">
        ko.validation.init({
            registerExtenders: true,
            messagesOnModified: true,
            insertMessages: true,
            parseInputAttributes: true,
            errorClass: 'errorStyle',
            messageTemplate: null

        }, true);

        function Sale(data) {
            var self = this;
            self.Id = ko.observable('')
            self.CustomerId = ko.observable('');
            self.ProductId = ko.observable('');
            self.StoreId = ko.observable('');
            self.CustomerName = ko.observable('');
            self.ProductName = ko.observable('');
            self.StoreName = ko.observable('');
            self.DateSold = ko.observable('').extend({
                required: {
                    params:true,
                   message:('please enter the date')
                }
                });



            // Subcribers to update data's name when dropdown list values are selected.
            self.CustomerId.subscribe(function (newValue) {
                if (newValue) {
                    try {
                        var elem = document.querySelector("#CustomerId option[value='" + self.CustomerId() + "']");
                        if (elem)
                            self.CustomerName(elem.text);
                    } catch (e) {
                        //Do nothing.
                    }
                };
            });

            self.ProductId.subscribe(function (newValue) {
                if (newValue) {
                    try {
                        var elem = document.querySelector("#ProductId option[value='" + self.ProductId() + "']");
                        if (elem)
                            self.ProductName(elem.text);
                    } catch (e) {
                        //Do nothing.
                    }


                };
            });
            self.StoreId.subscribe(function (newValue) {
                if (newValue) {
                    try {
                        var elem = document.querySelector("#StoreId option[value='" + self.StoreId() + "']");
                        if (elem)
                            self.StoreName(elem.text);
                    } catch (e) {
                        //Do nothing.
                    }


                };
            });

            // Constructor
            if (data) {
                self.Id(data.Id);
                self.CustomerId(data.CustomerId);
                self.ProductId(data.ProductId);
                self.StoreId(data.StoreId);
                self.CustomerName(data.CustomerName);
                self.ProductName(data.ProductName);
                self.StoreName(data.StoreName);
                self.DateSold(data.ReturnDateForDisplay);
            }

            self.toArray = function () {
                var output = {
                    Id: self.Id(),
                    CustomerId: self.CustomerId(),
                    ProductId: self.ProductId(),
                    StoreId: self.StoreId(),
                    DateSold: self.DateSold(),
                    CustomerName: self.CustomerName(),
                    ProductName: self.ProductName(),
                    StoreName: self.StoreName(),
                    ReturnDateForDisplay: self.DateSold()
                };
                return output;
            }

        }
        function SaleViewModel() {
            var self = this;
            self.ProductSolds = ko.observableArray();
            self.selectedSale = new Sale();
            self.newSale = new Sale();


            // Response to view details button.
            self.viewSale = function (data) {
                self.selectedSale = data;
                var options = { "backdrop": "static", keyboard: true };
                // Call the Details action, expect to get the partial view HTML document.
                $.ajax({
                    type: "GET",
                    url: "/ProductSolds/Details",
                    datatype: "html",
                    success: function (data) {
                        // Insert the partial view HTML into the bootstrap modal.
                        $('#my-modal-content').html(data);
                        $('#my-modal').modal(options);
                        // Apply binding to the newly inserted html section.
                        //debugger;
                        ko.applyBindings(self, document.getElementById('sale-details'));
                        $('#my-modal').modal('show');
                    }
                });
            };

            // Response to 'create sale' button.
            self.createSale = function () {
                self.selectedSale = new Sale();
                var options = { "backdrop": "static", keyboard: true };
                //debugger;
                $.ajax({
                    type: "GET",
                    url: "/ProductSolds/Create",
                    datatype: "html",
                    success: function (data) {
                        // Insert the partial view HTML into the bootstrap modal.
                        $('#my-modal-content').html(data);
                        $('#my-modal').modal(options);
                        // Apply binding to the newly inserted html section.
                        ko.applyBindings(self, document.getElementById('create-sale-form'));
                        $('#my-modal').modal('show');
                    }
                });
            };

            // Response to the 'save' button in the create new sale form.
            self.saveSale = function (data) {
                // Calling ajax to save data to sever.
                $.ajax({
                    type: "POST",
                    url: "/ProductSolds/Create",
                    data: $('#create-sale-form').serialize(),
                    datatype: "json",
                    success: function (data) {
                        if (data > 0) {
                            // Get the new ID.
                            self.selectedSale.Id(data);
                            // formate the date data.
                            self.selectedSale.DateSold(self.formatDate(self.selectedSale.DateSold()));
                            // Add the new sale into 'ProductSolds' array.

                            self.ProductSolds.push(self.selectedSale);
                            //alert("Please enter date");
                            $('#my-modal').modal('hide');
                        } else {
                            alert("Please enter Date");
                            $('#my-modal').modal('hide');

                        }
                    }
                });
            };

            // Reponse to 'Edit' button.
            self.editSale = function (data) {
                self.selectedSale = data;
                self.newSale = new Sale(data.toArray());
                self.newSale.errors = ko.validation.group(self.newSale);
                var options = { "backdrop": "static", keyboard: true };
                // Call the Details action to get the partial view HTML document.
                $.ajax({
                    type: "GET",
                    url: "/ProductSolds/Edit",
                    datatype: "html",
                    success: function (data) {
                        // Insert the partial view HTML into the bootstrap modal.
                        $('#my-modal-content').html(data);
                        $('#my-modal').modal(options);
                        // Apply binding to the newly inserted html section.
                        ko.applyBindings(self, document.getElementById('edit-sale-form'));
                        $('#my-modal').modal('show');
                    }
                });
            };
            // Reponse to 'Save' button in Edit Sale form.
            self.editConfirmed = function () {
                //debugger;
                if (self.newSale.errors().length === 0) {
                    //debugger;
                    // Save new data to the database.
                    $.ajax({
                        type: "POST",
                        url: "/ProductSolds/Edit",
                        data: $('#edit-sale-form').serialize(),
                        success: function (data) {
                            // Update viewModel array.
                            //debugger;
                            self.ProductSolds.replace(self.selectedSale, self.newSale);
                            $('#my-modal').modal('hide');
                        },
                    });
                } else {
                    alert("Error! Please check your submission.");

                }

            };


            //Response to 'Delete' button
            self.deleteSale = function (data) {

                self.selectedSale = data;
                //alert(self.selectedSale.CustomerName());
                var options = { "backdrop": "static", keyboard: true };
                // Call the Delete action to get the partial view HTML document.
                 //debugger;
                $.ajax({
                    type: "GET",
                    url: "/ProductSolds/Delete",
                    datatype: "html",
                    success: function (data) {
                        // Insert the partial view HTML into the bootstrap modal.
                        $('#my-modal-content').html(data);
                        $('#my-modal').modal(options);
                        // Apply binding to the newly inserted html section.
                        ko.applyBindings(self, document.getElementById('deleteSale'));
                        $('#my-modal').modal('show');
                    }
                });
            };

            // Delete confirmed.
            self.deleteConfirmed = function () {
                self.ProductSolds.remove(self.selectedSale);
                $('#my-modal').modal('hide');
                $.ajax({
                    type: "POST",
                    url: "/ProductSolds/Delete",
                    data: $('#delete-sale-form').serialize(),
                    datatype: "html"
                });
            };

            
            self.formatDate = function (string) {
                var date = new Date(string);
                var output = (date.getDate() + '/' + date.getMonth()  + '/' + date.getFullYear());
                return output;
            };

        };

        ko.validation.registerExtenders();
        $("document").ready(function () {

            var viewModel = new SaleViewModel();
            $.get('/ProductSolds/ProductSoldList', function (data) {
                var sale;
                $.each(data, function (i, item) {
                    sale = new Sale(item);
                    viewModel.ProductSolds.push(sale);

                })
            });
            ko.applyBindings(viewModel);
        });
    </script>
}